spring.application.name=email-writer-sb

gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent
gemini.api.key=AIzaSyCoMJ2_jV22-xyk5_wM9-BEGVMAeVU4z_8
# Set maximum allowed file size (e.g., 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB